import type { Metadata } from 'next';
import './globals.css';
import QueryProvider from './QueryProvider';
import { Ubuntu_Mono } from 'next/font/google';
import localFont from 'next/font/local';

const ubuntu = Ubuntu_Mono({
  variable: '--font-ubuntu-mono',
  subsets: ['latin'],
  weight: ['400', '700'],
});
const konkhmerSleokchher = localFont({
  src: '../../public/fonts/KonkhmerSleokchher-Regular.ttf',
  variable: '--font-konkhmer-sleokchher',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.variable} ${konkhmerSleokchher.variable} antialiased`}
      >
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
