import type { Metadata } from 'next';
import './globals.css';
import QueryProvider from './QueryProvider';
import { Ubuntu_Mono } from 'next/font/google';
import localFont from 'next/font/local';

const ubuntu = Ubuntu_Mono({
  variable: '--font-ubuntu-mono',
  subsets: ['latin'],
  weight: ['400', '700'],
});
const konkhmerSleokchher = localFont({
  src: '../../public/fonts/KonkhmerSleokchher-Regular.ttf',
  variable: '--font-konkhmer-sleokchher',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Create Next App',
    description: 'Generated by create next app',
    url: 'https://i.pinimg.com/736x/96/4e/a8/964ea8fd663443907e53b5262001180c.jpg',
    siteName: 'Create Next App',
    images: [
      {
        url: 'https://i.pinimg.com/736x/f9/fa/72/f9fa72bc4e11357047c5cfb5f07364ba.jpg',
        width: 500,
        height: 500,
        alt: 'Open Graph Image',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.variable} ${konkhmerSleokchher.variable} antialiased`}
      >
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
